import { defineConfig } from 'tsup'
export default defineConfig({
  entry: {
    server: 'apps/api/src/server.ts',
    worker: 'apps/api/src/worker.ts',
    migrate: 'packages/database/src/migrate.ts',
    'admin-bootstrap': 'scripts/admin/bootstrap.ts',
    'content-bootstrap-danetki': 'scripts/content/bootstrap-danetki.ts',
    'content-bootstrap-connections': 'scripts/content/bootstrap-connections.ts',
    'content-bootstrap-territory': 'scripts/content/bootstrap-territory.ts',
    'content-import-dtf-comments': 'scripts/content/import-dtf-comment-pack.ts',
    'content-import-game-hints': 'scripts/content/import-game-plot-hints.ts',
    'content-import-kpop-special': 'scripts/content/import-kpop-special.ts',
    'content-migrate-media': 'scripts/content/migrate-media.ts',
    'content-repair-active-catalog': 'scripts/content/repair-active-catalog.ts',
    'content-replace-music-catalog': 'scripts/content/replace-music-catalog.ts',
    'series-enrich-active-production': 'scripts/series/enrich-active-production.ts',
    'movie-repair-active-production': 'scripts/movies/repair-active-production.ts',
    'production-maintenance': 'scripts/maintenance/run-production-maintenance.ts',
    'city-hints': 'scripts/cities/operate-city-hints.ts',
    'city-facts': 'scripts/cities/operate-city-facts.ts',
    'city-facts-web': 'scripts/cities/review-city-facts.ts',
    'city-facts-final': 'scripts/cities/consolidate-city-facts.ts',
    'city-content-finalize': 'scripts/cities/finalize-city-content.ts',
  },
  format: ['esm'], platform: 'node', target: 'node24', outDir: 'apps/api/dist', clean: true,
})
